controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


app_contact:
    path: /app_contact
    controller: App\Controller\YourController::yourAction

      #[Route('/contact', name: 'app_contact')]